### ISSUE TITLE
文章小问题反馈

### ISSUE THREAD

**Issue by safly** [brickyang/brickyang.github.io#1]
Hello, 博客很详细，很简洁，先赞一个！
https://brickyang.github.io/2017/01/14/CentOS-7-%E5%AE%89%E8%A3%85-Shadowsocks-%E5%AE%A2%E6%88%B7%E7%AB%AF/
这篇文章中
forward-socks5t / 127.0.0.1:0
应为
forward-socks5t / 127.0.0.1:0 .
后面带一个.，否则报错Error: Wrong number of parameters for forward-socks5t in configuration file.
官方文档里是这么写的，#        forward-socks5t   /               127.0.0.1:9050 .
很荣幸能提交issue，希望成为朋友，向前辈学习！支持原创，加油！

**Comment by brickyang** [comment]
已修改。Thanks。
